# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd3f803b8fd6eb09adbd7d97d2f20963170878d406c12c37866ffd7163dfcd10ef8949ed800d00916a577c14e1b5da7bd8060ed76da673b46b2ac87604b59679

test:
  secret_key_base: e9ce03daec61f7f1f995f7715abcc41ad6dba9cb6629e70050165bcf0edec5d1ef405d16b9d9b4faff57cebcee25d58a928c9fc33f5ffdc095be5889ec12f012

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
